//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.WebServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aparatos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Aparatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        private decimal MagnitudField;
        
        private decimal ProfundidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeolocalizacionField;
        
        private System.DateTime FechaRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Magnitud {
            get {
                return this.MagnitudField;
            }
            set {
                if ((this.MagnitudField.Equals(value) != true)) {
                    this.MagnitudField = value;
                    this.RaisePropertyChanged("Magnitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Profundidad {
            get {
                return this.ProfundidadField;
            }
            set {
                if ((this.ProfundidadField.Equals(value) != true)) {
                    this.ProfundidadField = value;
                    this.RaisePropertyChanged("Profundidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Geolocalizacion {
            get {
                return this.GeolocalizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.GeolocalizacionField, value) != true)) {
                    this.GeolocalizacionField = value;
                    this.RaisePropertyChanged("Geolocalizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServ.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aparato del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarAparato", ReplyAction="*")]
        WindowsService.WebServ.RegistrarAparatoResponse RegistrarAparato(WindowsService.WebServ.RegistrarAparatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarAparato", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsService.WebServ.RegistrarAparatoResponse> RegistrarAparatoAsync(WindowsService.WebServ.RegistrarAparatoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarAparatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarAparato", Namespace="http://tempuri.org/", Order=0)]
        public WindowsService.WebServ.RegistrarAparatoRequestBody Body;
        
        public RegistrarAparatoRequest() {
        }
        
        public RegistrarAparatoRequest(WindowsService.WebServ.RegistrarAparatoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarAparatoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsService.WebServ.Aparatos aparato;
        
        public RegistrarAparatoRequestBody() {
        }
        
        public RegistrarAparatoRequestBody(WindowsService.WebServ.Aparatos aparato) {
            this.aparato = aparato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarAparatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarAparatoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsService.WebServ.RegistrarAparatoResponseBody Body;
        
        public RegistrarAparatoResponse() {
        }
        
        public RegistrarAparatoResponse(WindowsService.WebServ.RegistrarAparatoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegistrarAparatoResponseBody {
        
        public RegistrarAparatoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsService.WebServ.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsService.WebServ.WebServiceSoap>, WindowsService.WebServ.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsService.WebServ.RegistrarAparatoResponse WindowsService.WebServ.WebServiceSoap.RegistrarAparato(WindowsService.WebServ.RegistrarAparatoRequest request) {
            return base.Channel.RegistrarAparato(request);
        }
        
        public void RegistrarAparato(WindowsService.WebServ.Aparatos aparato) {
            WindowsService.WebServ.RegistrarAparatoRequest inValue = new WindowsService.WebServ.RegistrarAparatoRequest();
            inValue.Body = new WindowsService.WebServ.RegistrarAparatoRequestBody();
            inValue.Body.aparato = aparato;
            WindowsService.WebServ.RegistrarAparatoResponse retVal = ((WindowsService.WebServ.WebServiceSoap)(this)).RegistrarAparato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsService.WebServ.RegistrarAparatoResponse> WindowsService.WebServ.WebServiceSoap.RegistrarAparatoAsync(WindowsService.WebServ.RegistrarAparatoRequest request) {
            return base.Channel.RegistrarAparatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsService.WebServ.RegistrarAparatoResponse> RegistrarAparatoAsync(WindowsService.WebServ.Aparatos aparato) {
            WindowsService.WebServ.RegistrarAparatoRequest inValue = new WindowsService.WebServ.RegistrarAparatoRequest();
            inValue.Body = new WindowsService.WebServ.RegistrarAparatoRequestBody();
            inValue.Body.aparato = aparato;
            return ((WindowsService.WebServ.WebServiceSoap)(this)).RegistrarAparatoAsync(inValue);
        }
    }
}
